---
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
executors:
  boot-linux:
    machine:
      enabled: true
      image: ubuntu-1604:202010-01
commands:
  git-checkout:
    steps:
      - checkout
      - run: mv install-scripts cross-build-release/
  build-n-publish-debian:
    steps:
      - run: sudo apt-get -y install wget
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-ci.sh
          no_output_timeout: 20m
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run:
          command: |
            .circleci/publish-cloudsmith.sh img bbn-cica/bbn-open ${PKG_DISTRO}/${PKG_RELEASE}
          no_output_timeout: 40m
  do-all:
    steps:
      - git-checkout
      - build-n-publish-debian
jobs:
  build-raspbian-bullseye-arm32:
    executor: boot-linux
    environment:
      - DOCKER_IMAGE=arm32v7/debian:bullseye
      - CONTAINER_DISTRO=debian:bullseye
      - PKG_RELEASE=raspbian
      - PKG_DISTRO=bullseye
      - PKG_ARCH=armhf
      - EMU=on
    steps:
      - do-all
  build-raspbian-bullseye-arm64:
    executor: boot-linux
    environment:
      - DOCKER_IMAGE=arm64v8/debian:bullseye
      - CONTAINER_DISTRO=debian:bullseye
      - PKG_RELEASE=raspbian
      - PKG_DISTRO=bullseye
      - PKG_ARCH=arm64
      - EMU=on
    steps:
      - do-all
workflows:
  version: 2
  build_all:
    jobs:
      - build-raspbian-bullseye-arm32
      - build-raspbian-bullseye-arm64
